- generic [ref=e1]:
  - generic [ref=e3]:
    - generic [ref=e9]:
      - link "Creator" [ref=e900] [cursor=pointer]:
        - /url: /
        - img [ref=e13]
        - generic [ref=e74]: Creator
      - generic [ref=e77]:
        - combobox "AhmadPSN AhmadPSN" [ref=e901] [cursor=pointer]:
          - generic [ref=e79]:
            - img "AhmadPSN" [ref=e902]
            - generic "AhmadPSN" [ref=e903]
        - textbox: "126595306"
        - img
        - group
      - link "Home" [ref=e904] [cursor=pointer]:
        - /url: /
        - img [ref=e88]
        - generic [ref=e91]: Home
      - link "Creations" [ref=e905] [cursor=pointer]:
        - /url: /dashboard/creations
        - img [ref=e95]
        - generic [ref=e98]: Creations
      - link "Learn" [ref=e906] [cursor=pointer]:
        - /url: https://create.roblox.com/docs?navFromCreatorHub=true
        - img [ref=e102]
        - generic [ref=e106]: Learn
      - link "Store" [ref=e907] [cursor=pointer]:
        - /url: https://create.roblox.com/store/
        - img [ref=e110]
        - generic [ref=e113]: Store
      - link "Forum" [ref=e908] [cursor=pointer]:
        - /url: https://devforum.roblox.com
        - img [ref=e117]
        - generic [ref=e122]: Forum
      - separator [ref=e123]
      - link "Finances" [ref=e909] [cursor=pointer]:
        - /url: /dashboard/devex
        - img [ref=e127]
        - generic [ref=e130]: Finances
      - link "Analytics" [ref=e910] [cursor=pointer]:
        - /url: /dashboard/analytics
        - img [ref=e134]
        - generic [ref=e144]: Analytics
      - link "Ads" [ref=e911] [cursor=pointer]:
        - /url: https://create.roblox.com/advertise
        - img [ref=e148]
        - generic [ref=e151]: Ads
      - separator [ref=e152]
      - button "All tools" [ref=e912] [cursor=pointer]:
        - img [ref=e156]
        - generic [ref=e167]: All tools
      - link "Roblox.com" [ref=e913] [cursor=pointer]:
        - /url: https://roblox.com/
        - img [ref=e171]
        - generic [ref=e174]: Roblox.com
      - button "Studio" [ref=e914] [cursor=pointer]:
        - img [ref=e178]
        - generic [ref=e182]: Studio
    - generic [ref=e16]:
      - generic [ref=e17]:
        - button "menu" [ref=e915] [cursor=pointer]:
          - img [ref=e19]
        - heading "API Extensions" [level=1] [ref=e916]
      - generic [ref=e21]:
        - button "Search" [ref=e917] [cursor=pointer]:
          - img [ref=e24]
        - button "Notifications" [ref=e918] [cursor=pointer]:
          - img [ref=e189]
        - button "AhmadPSN" [ref=e919] [cursor=pointer]:
          - img "AhmadPSN" [ref=e920]
    - generic [ref=e31]:
      - generic [ref=e249]:
        - generic [ref=e250]:
          - button "cancel" [ref=e921] [cursor=pointer]:
            - img [ref=e252]
          - generic [ref=e254]: New API Key
          - button "Save & Generate Key" [ref=e922] [cursor=pointer]:
            - generic [ref=e366]: Save & Generate Key
        - separator [ref=e256]
        - generic [ref=e258]:
          - button "1 General Information" [expanded] [ref=e923] [cursor=pointer]:
            - generic [ref=e262]:
              - generic [ref=e264]: "1"
              - generic [ref=e265]: General Information
            - img [ref=e267]
          - region [ref=e272]:
            - generic [ref=e274]:
              - generic [ref=e275]:
                - generic [ref=e276]:
                  - generic [ref=e277]:
                    - text: Name
                    - generic [ref=e278]: (Required)
                  - paragraph [ref=e279]: Give your API Key a unique name
                - generic [ref=e281]:
                  - generic [ref=e283]:
                    - textbox "Name(Required) 22/64" [ref=e924]:
                      - /placeholder: Name your API Key
                      - text: The Oath dev publisher
                    - group
                  - generic [ref=e285]: 22/64
              - generic [ref=e286]:
                - generic [ref=e287]:
                  - generic [ref=e288]: Description
                  - paragraph [ref=e289]: Enter an optional description for your API key
                - generic [ref=e291]:
                  - generic [ref=e293]:
                    - textbox "Description 0/1000" [ref=e925]:
                      - /placeholder: Enter a description here...
                    - group
                  - generic [ref=e295]: 0/1000
        - generic [ref=e297]:
          - button "2 Access Permissions" [expanded] [ref=e926] [cursor=pointer]:
            - generic [ref=e301]:
              - generic [ref=e303]: "2"
              - generic [ref=e304]: Access Permissions
            - img [ref=e306]
          - region [ref=e311]:
            - generic [ref=e313]:
              - generic [ref=e314]:
                - generic [ref=e318]:
                  - img [ref=e319]
                  - combobox "Select API System" [ref=e927]
                  - button "Open" [ref=e928] [cursor=pointer]:
                    - img [ref=e324]
                  - group
                - generic [ref=e327]: Set the minimum permissions for your application to minimize impact in case your key gets compromised.
              - generic [ref=e328]:
                - generic [ref=e794]:
                  - generic [ref=e795]:
                    - generic [ref=e796]:
                      - generic [ref=e797]: universe-datastores
                      - button "Remove API System" [ref=e929] [cursor=pointer]:
                        - img [ref=e799]
                    - generic [ref=e801]:
                      - checkbox "Restrict by Experience" [ref=e930] [cursor=pointer]
                      - generic [ref=e807]: Restrict by Experience
                  - separator [ref=e808]
                  - generic [ref=e811]:
                    - paragraph [ref=e813]: Select operations for ALL data stores in your experience. Current and future.
                    - generic [ref=e816]:
                      - generic [ref=e818]:
                        - combobox "Select Operations to Add" [expanded] [active] [ref=e931]
                        - button "Close" [ref=e963] [cursor=pointer]:
                          - img [ref=e822]
                        - group
                      - listbox [ref=e964]:
                        - listitem [ref=e965]:
                          - generic [ref=e966]: universe-datastores.objects
                          - list [ref=e967]:
                            - option "read" [ref=e968] [cursor=pointer]:
                              - generic [ref=e970]: read
                            - option "create" [ref=e971] [cursor=pointer]:
                              - generic [ref=e973]: create
                            - option "update" [ref=e974] [cursor=pointer]:
                              - generic [ref=e976]: update
                            - option "delete" [ref=e977] [cursor=pointer]:
                              - generic [ref=e979]: delete
                            - option "list" [ref=e980] [cursor=pointer]:
                              - generic [ref=e982]: list
                        - listitem [ref=e983]:
                          - generic [ref=e984]: universe-datastores.versions
                          - list [ref=e985]:
                            - option "read" [ref=e986] [cursor=pointer]:
                              - generic [ref=e988]: read
                            - option "list" [ref=e989] [cursor=pointer]:
                              - generic [ref=e991]: list
                        - listitem [ref=e992]:
                          - generic [ref=e993]: universe-datastores.control
                          - list [ref=e994]:
                            - option "create" [ref=e995] [cursor=pointer]:
                              - generic [ref=e997]: create
                            - option "delete" [ref=e998] [cursor=pointer]:
                              - generic [ref=e1000]: delete
                            - option "list" [ref=e1001] [cursor=pointer]:
                              - generic [ref=e1003]: list
                            - option "snapshot" [ref=e1004] [cursor=pointer]:
                              - generic [ref=e1006]: snapshot
                - generic [ref=e473]:
                  - generic [ref=e474]:
                    - generic [ref=e475]:
                      - generic [ref=e476]: universe-places
                      - button "Remove API System" [ref=e933] [cursor=pointer]:
                        - img [ref=e478]
                    - generic [ref=e480]:
                      - checkbox "Restrict by Experience" [checked] [ref=e934] [cursor=pointer]
                      - generic [ref=e486]: Restrict by Experience
                      - generic [ref=e604]:
                        - img [ref=e606]
                        - combobox "Search for an experience" [ref=e935]
                        - button "Open" [ref=e936] [cursor=pointer]:
                          - img [ref=e611]
                        - group
                  - separator [ref=e487]
                  - generic [ref=e650]:
                    - generic [ref=e652]:
                      - text: The Oath (dev)
                      - button "Copy experience ID to clipboard" [ref=e937] [cursor=pointer]:
                        - img [ref=e654]
                      - button "Remove Experience" [ref=e938] [cursor=pointer]:
                        - img [ref=e657]
                      - button "Open in New Tab" [ref=e939] [cursor=pointer]:
                        - img [ref=e660]
                    - generic [ref=e663]:
                      - paragraph [ref=e665]: "\"Write\" will apply to all existing places in the experience."
                      - generic [ref=e670]:
                        - button "universe-places:write" [ref=e940] [cursor=pointer]:
                          - generic [ref=e683]: universe-places:write
                          - img [ref=e684]
                        - combobox [ref=e686]
                        - button "Open" [ref=e941] [cursor=pointer]:
                          - img [ref=e674]
                        - group
        - generic [ref=e330]:
          - button "3 Security" [expanded] [ref=e942] [cursor=pointer]:
            - generic [ref=e334]:
              - generic [ref=e336]: "3"
              - generic [ref=e337]: Security
            - img [ref=e339]
          - region [ref=e344]:
            - generic [ref=e346]:
              - generic [ref=e348]:
                - checkbox "Restrict IPs" [ref=e943] [cursor=pointer]
                - text: Restrict which IP addresses this API Key can be used from
              - generic [ref=e353]:
                - generic [ref=e354]:
                  - generic [ref=e356]: Expiration
                  - text: The API Key will expire either on the specified expiration date or after 60 days of inactivity, whichever comes first.
                - generic [ref=e360]:
                  - combobox "No Expiration" [ref=e944] [cursor=pointer]
                  - textbox: "0"
                  - img
                  - group
        - generic [ref=e362]: A unique name is required to generate an API key.
        - button "Save & Generate Key" [ref=e945] [cursor=pointer]:
          - generic [ref=e369]: Save & Generate Key
      - generic [ref=e39]:
        - generic [ref=e40]:
          - generic [ref=e241]: ©2026 Roblox Corporation. All rights reserved.
          - generic [ref=e41]:
            - link "Terms" [ref=e946] [cursor=pointer]:
              - /url: https://www.roblox.com/info/terms
            - text: ·
            - link "Privacy" [ref=e947] [cursor=pointer]:
              - /url: https://www.roblox.com/info/privacy
            - text: ·
            - link "Accessibility" [ref=e948] [cursor=pointer]:
              - /url: https://www.roblox.com/info/accessibility
            - text: ·
            - link "Support" [ref=e949] [cursor=pointer]:
              - /url: https://www.roblox.com/info/help
            - text: ·
            - button "Your Privacy Choices" [ref=e950] [cursor=pointer]:
              - generic [ref=e247]: Your Privacy Choices
        - generic [ref=e42]:
          - link "X" [ref=e951] [cursor=pointer]:
            - /url: https://x.com/Roblox
            - button "X" [ref=e952]:
              - img [ref=e45]
          - link "Facebook" [ref=e953] [cursor=pointer]:
            - /url: https://www.facebook.com/Roblox/
            - button "Facebook" [ref=e954]:
              - img [ref=e49]
          - link "LinkedIn" [ref=e955] [cursor=pointer]:
            - /url: https://www.linkedin.com/company/roblox
            - button "LinkedIn" [ref=e956]:
              - img [ref=e53]
          - link "Instagram" [ref=e957] [cursor=pointer]:
            - /url: https://www.instagram.com/roblox/
            - button "Instagram" [ref=e958]:
              - img [ref=e57]
          - link "YouTube" [ref=e959] [cursor=pointer]:
            - /url: https://www.youtube.com/Roblox
            - button "YouTube" [ref=e960]:
              - img [ref=e62]
        - link "English" [ref=e961] [cursor=pointer]:
          - /url: https://roblox.com/my/account
          - button "English" [ref=e962]:
            - img [ref=e68]
            - generic [ref=e70]: English
  - alert [ref=e71]
  - iframe