- generic [active] [ref=e1]:
  - generic [ref=e3]:
    - generic [ref=e9]:
      - link "Creator" [ref=e72] [cursor=pointer]:
        - /url: /
        - img [ref=e13]
        - generic [ref=e74]: Creator
      - generic [ref=e77]:
        - combobox "AhmadPSN AhmadPSN" [ref=e78] [cursor=pointer]:
          - generic [ref=e79]:
            - img "AhmadPSN" [ref=e82]
            - generic "AhmadPSN" [ref=e84]
        - textbox: "126595306"
        - img
        - group
      - link "Home" [ref=e86] [cursor=pointer]:
        - /url: /
        - img [ref=e88]
        - generic [ref=e91]: Home
      - link "Creations" [ref=e93] [cursor=pointer]:
        - /url: /dashboard/creations
        - img [ref=e95]
        - generic [ref=e98]: Creations
      - link "Learn" [ref=e100] [cursor=pointer]:
        - /url: https://create.roblox.com/docs?navFromCreatorHub=true
        - img [ref=e102]
        - generic [ref=e106]: Learn
      - link "Store" [ref=e108] [cursor=pointer]:
        - /url: https://create.roblox.com/store/
        - img [ref=e110]
        - generic [ref=e113]: Store
      - link "Forum" [ref=e115] [cursor=pointer]:
        - /url: https://devforum.roblox.com
        - img [ref=e117]
        - generic [ref=e122]: Forum
      - separator [ref=e123]
      - link "Finances" [ref=e125] [cursor=pointer]:
        - /url: /dashboard/devex
        - img [ref=e127]
        - generic [ref=e130]: Finances
      - link "Analytics" [ref=e132] [cursor=pointer]:
        - /url: /dashboard/analytics
        - img [ref=e134]
        - generic [ref=e144]: Analytics
      - link "Ads" [ref=e146] [cursor=pointer]:
        - /url: https://create.roblox.com/advertise
        - img [ref=e148]
        - generic [ref=e151]: Ads
      - separator [ref=e152]
      - button "All tools" [ref=e154] [cursor=pointer]:
        - img [ref=e156]
        - generic [ref=e167]: All tools
      - link "Roblox.com" [ref=e169] [cursor=pointer]:
        - /url: https://roblox.com/
        - img [ref=e171]
        - generic [ref=e174]: Roblox.com
      - button "Studio" [ref=e176] [cursor=pointer]:
        - img [ref=e178]
        - generic [ref=e182]: Studio
    - generic [ref=e16]:
      - generic [ref=e17]:
        - button "menu" [ref=e18] [cursor=pointer]:
          - img [ref=e19]
        - heading "API Extensions" [level=1] [ref=e185]
      - generic [ref=e21]:
        - button "Search" [ref=e23] [cursor=pointer]:
          - img [ref=e24]
        - button "Notifications" [ref=e188] [cursor=pointer]:
          - img [ref=e189]
        - button "AhmadPSN" [ref=e191] [cursor=pointer]:
          - img "AhmadPSN" [ref=e196]
    - generic [ref=e31]:
      - generic [ref=e249]:
        - generic [ref=e250]:
          - button "cancel" [ref=e251] [cursor=pointer]:
            - img [ref=e252]
          - generic [ref=e254]: New API Key
          - generic "A unique name is required to generate an API key." [ref=e255]:
            - button "Save & Generate Key" [disabled]:
              - generic: Save & Generate Key
        - separator [ref=e256]
        - generic [ref=e258]:
          - button "1 General Information" [expanded] [ref=e259] [cursor=pointer]:
            - generic [ref=e262]:
              - generic [ref=e264]: "1"
              - generic [ref=e265]: General Information
            - img [ref=e267]
          - region [ref=e272]:
            - generic [ref=e274]:
              - generic [ref=e275]:
                - generic [ref=e276]:
                  - generic [ref=e277]:
                    - text: Name
                    - generic [ref=e278]: (Required)
                  - paragraph [ref=e279]: Give your API Key a unique name
                - generic [ref=e281]:
                  - generic [ref=e283]:
                    - textbox "Name(Required) 0/64" [ref=e284]:
                      - /placeholder: Name your API Key
                    - group
                  - generic [ref=e285]: 0/64
              - generic [ref=e286]:
                - generic [ref=e287]:
                  - generic [ref=e288]: Description
                  - paragraph [ref=e289]: Enter an optional description for your API key
                - generic [ref=e291]:
                  - generic [ref=e293]:
                    - textbox "Description 0/1000" [ref=e294]:
                      - /placeholder: Enter a description here...
                    - group
                  - generic [ref=e295]: 0/1000
        - generic [ref=e297]:
          - button "2 Access Permissions" [expanded] [ref=e298] [cursor=pointer]:
            - generic [ref=e301]:
              - generic [ref=e303]: "2"
              - generic [ref=e304]: Access Permissions
            - img [ref=e306]
          - region [ref=e311]:
            - generic [ref=e313]:
              - generic [ref=e314]:
                - generic [ref=e318]:
                  - img [ref=e319]
                  - combobox "Select API System" [ref=e321]
                  - button "Open" [ref=e323] [cursor=pointer]:
                    - img [ref=e324]
                  - group
                - generic [ref=e327]: Set the minimum permissions for your application to minimize impact in case your key gets compromised.
              - generic [ref=e328]: No permissions added yet.
        - generic [ref=e330]:
          - button "3 Security" [expanded] [ref=e331] [cursor=pointer]:
            - generic [ref=e334]:
              - generic [ref=e336]: "3"
              - generic [ref=e337]: Security
            - img [ref=e339]
          - region [ref=e344]:
            - generic [ref=e346]:
              - generic [ref=e348]:
                - checkbox "Restrict IPs" [ref=e351] [cursor=pointer]
                - text: Restrict which IP addresses this API Key can be used from
              - generic [ref=e353]:
                - generic [ref=e354]:
                  - generic [ref=e356]: Expiration
                  - text: The API Key will expire either on the specified expiration date or after 60 days of inactivity, whichever comes first.
                - generic [ref=e360]:
                  - combobox "No Expiration" [ref=e361] [cursor=pointer]
                  - textbox: "0"
                  - img
                  - group
        - generic [ref=e362]: A unique name is required to generate an API key.
        - generic "A unique name is required to generate an API key." [ref=e364]:
          - button "Save & Generate Key" [disabled]:
            - generic: Save & Generate Key
      - generic [ref=e39]:
        - generic [ref=e40]:
          - generic [ref=e241]: ©2026 Roblox Corporation. All rights reserved.
          - generic [ref=e41]:
            - link "Terms" [ref=e242] [cursor=pointer]:
              - /url: https://www.roblox.com/info/terms
            - text: ·
            - link "Privacy" [ref=e243] [cursor=pointer]:
              - /url: https://www.roblox.com/info/privacy
            - text: ·
            - link "Accessibility" [ref=e244] [cursor=pointer]:
              - /url: https://www.roblox.com/info/accessibility
            - text: ·
            - link "Support" [ref=e245] [cursor=pointer]:
              - /url: https://www.roblox.com/info/help
            - text: ·
            - button "Your Privacy Choices" [ref=e246] [cursor=pointer]:
              - generic [ref=e247]: Your Privacy Choices
        - generic [ref=e42]:
          - link "X" [ref=e43] [cursor=pointer]:
            - /url: https://x.com/Roblox
            - button "X" [ref=e44]:
              - img [ref=e45]
          - link "Facebook" [ref=e47] [cursor=pointer]:
            - /url: https://www.facebook.com/Roblox/
            - button "Facebook" [ref=e48]:
              - img [ref=e49]
          - link "LinkedIn" [ref=e51] [cursor=pointer]:
            - /url: https://www.linkedin.com/company/roblox
            - button "LinkedIn" [ref=e52]:
              - img [ref=e53]
          - link "Instagram" [ref=e55] [cursor=pointer]:
            - /url: https://www.instagram.com/roblox/
            - button "Instagram" [ref=e56]:
              - img [ref=e57]
          - link "YouTube" [ref=e60] [cursor=pointer]:
            - /url: https://www.youtube.com/Roblox
            - button "YouTube" [ref=e61]:
              - img [ref=e62]
        - link "English" [ref=e65] [cursor=pointer]:
          - /url: https://roblox.com/my/account
          - button "English" [ref=e66]:
            - img [ref=e68]
            - generic [ref=e70]: English
  - alert [ref=e71]
  - iframe