- generic [active] [ref=e1]:
  - generic [ref=e4]:
    - generic [ref=e7]:
      - generic [ref=e8]:
        - button "menu" [ref=e9] [cursor=pointer]:
          - img [ref=e10]
        - navigation "breadcrumbs" [ref=e13]:
          - list [ref=e14]:
            - listitem [ref=e15]:
              - link "Learn" [ref=e16] [cursor=pointer]:
                - /url: /docs
            - listitem [ref=e17]: /
            - listitem [ref=e18]:
              - link "Studio" [ref=e19] [cursor=pointer]:
                - /url: /docs/en-us/studio
      - generic [ref=e20]:
        - generic [ref=e21]:
          - button "Search" [ref=e22] [cursor=pointer]:
            - img [ref=e23]
          - generic [ref=e26]:
            - img [ref=e29]
            - generic [ref=e31]:
              - generic [ref=e32]: Global search is here!
              - generic [ref=e33]: Search documentation and Creator Hub pages instantly. Press Ctrl + K to get started.
            - tooltip "Global search is here! Search documentation and Creator Hub pages instantly. Press Ctrl + K to get started." [ref=e34]:
              - generic [ref=e35]:
                - generic [ref=e36]: Global search is here!
                - generic [ref=e37]: Search documentation and Creator Hub pages instantly. Press Ctrl + K to get started.
        - button "Log In" [ref=e38] [cursor=pointer]:
          - generic [ref=e40]: Log In
    - generic [ref=e41]:
      - main [ref=e45]:
        - generic [ref=e47]:
          - heading "Connect to the Roblox Studio MCP server" [level=1] [ref=e50]
          - generic [ref=e51]:
            - button "English" [ref=e53] [cursor=pointer]:
              - generic [ref=e54]:
                - generic [ref=e55]: English
                - img [ref=e56]
            - button "Feedback" [ref=e59] [cursor=pointer]:
              - generic [ref=e60]:
                - generic [ref=e61]: Feedback
                - img [ref=e62]
            - button "Edit" [ref=e65] [cursor=pointer]:
              - button "Edit" [ref=e66]:
                - generic [ref=e67]:
                  - generic [ref=e68]: Edit
                  - img [ref=e69]
        - article [ref=e71]:
          - paragraph [ref=e72]:
            - text: The Roblox Studio MCP server is built into Roblox Studio. It implements the
            - link "Model Context Protocol (MCP)" [ref=e73] [cursor=pointer]:
              - /url: https://modelcontextprotocol.io/docs/getting-started/intro
            - text: ", an open standard that lets AI tools securely communicate with external applications. Once connected, your AI client can interact directly with your open Studio session, exploring the data model, writing scripts, running Luau code, and testing your experience in play mode."
          - paragraph [ref=e74]: "This guide shows you how to connect the Studio MCP server to popular AI clients. While the setup varies by client, the core idea is the same: you configure your client to connect to the MCP server and then send commands from the client to your active Studio session."
          - heading "copy header link" [level=2] [ref=e75]:
            - link "copy header link" [ref=e76] [cursor=pointer]:
              - /url: "#prerequisites"
              - text: Prerequisites
          - paragraph [ref=e77]: Before you can connect to the server, make sure you have the latest version of Roblox Studio and your preferred MCP client installed on your computer.
          - heading "copy header link" [level=2] [ref=e78]:
            - link "copy header link" [ref=e79] [cursor=pointer]:
              - /url: "#how-the-studio-mcp-server-works"
              - text: How the Studio MCP server works
          - paragraph [ref=e80]:
            - text: The server runs as a local process on your machine and communicates with the AI client using
            - generic [ref=e81]: stdio transport
            - text: ", which uses standard input/output streams. All actions are initiated through your AI client, which then sends a request through this channel to perform actions inside your Studio session."
          - paragraph [ref=e82]: "The server provides the following tools:"
          - table [ref=e84]:
            - rowgroup [ref=e85]:
              - row "Scripts" [ref=e86]:
                - columnheader "Scripts" [ref=e87]:
                  - generic [ref=e88]: Scripts
                - columnheader [ref=e89]
            - rowgroup [ref=e90]:
              - row "script_read Reads a scripts from the game using dot-notation paths (for example, game.ServerScriptService.MyScript). Supports reading entire scripts or specific line ranges." [ref=e91]:
                - cell "script_read" [ref=e92]:
                  - generic [ref=e93]: script_read
                - cell "Reads a scripts from the game using dot-notation paths (for example, game.ServerScriptService.MyScript). Supports reading entire scripts or specific line ranges." [ref=e94]:
                  - generic [ref=e95]: Reads a scripts from the game using dot-notation paths (for example, game.ServerScriptService.MyScript). Supports reading entire scripts or specific line ranges.
              - row "multi_edit Applies multiple edits to a script. If the target path doesn't exist, it creates a new script." [ref=e96]:
                - cell "multi_edit" [ref=e97]:
                  - generic [ref=e98]: multi_edit
                - cell "Applies multiple edits to a script. If the target path doesn't exist, it creates a new script." [ref=e99]
              - row "script_search Searches for scripts by name using fuzzy matching. Returns up to 10 results." [ref=e100]:
                - cell "script_search" [ref=e101]:
                  - generic [ref=e102]: script_search
                - cell "Searches for scripts by name using fuzzy matching. Returns up to 10 results." [ref=e103]
              - row "script_grep Searches for a string pattern across all script in the game. Returns up to 50 matches." [ref=e104]:
                - cell "script_grep" [ref=e105]:
                  - generic [ref=e106]: script_grep
                - cell "Searches for a string pattern across all script in the game. Returns up to 50 matches." [ref=e107]
            - rowgroup [ref=e108]:
              - row "Asset and content generation" [ref=e109]:
                - columnheader "Asset and content generation" [ref=e110]:
                  - generic [ref=e111]: Asset and content generation
                - columnheader [ref=e112]
            - rowgroup [ref=e113]:
              - row "generate_mesh Generates a textured 3D mesh." [ref=e114]:
                - cell "generate_mesh" [ref=e115]:
                  - generic [ref=e116]: generate_mesh
                - cell "Generates a textured 3D mesh." [ref=e117]
              - row "generate_material Generates custom material or texture." [ref=e118]:
                - cell "generate_material" [ref=e119]:
                  - generic [ref=e120]: generate_material
                - cell "Generates custom material or texture." [ref=e121]
              - row "insert_from_creator_store Inserts assets, plugins, and models from the Creator Store." [ref=e122]:
                - cell "insert_from_creator_store" [ref=e123]:
                  - generic [ref=e124]: insert_from_creator_store
                - cell "Inserts assets, plugins, and models from the Creator Store." [ref=e125]
            - rowgroup [ref=e126]:
              - row "Data model exploration" [ref=e127]:
                - columnheader "Data model exploration" [ref=e128]:
                  - generic [ref=e129]: Data model exploration
                - columnheader [ref=e130]
            - rowgroup [ref=e131]:
              - row "search_game_tree Explores the instance hierarchy as a flat JSON array. Supports filtering by path, instance type, and keywords." [ref=e132]:
                - cell "search_game_tree" [ref=e133]:
                  - generic [ref=e134]: search_game_tree
                - cell "Explores the instance hierarchy as a flat JSON array. Supports filtering by path, instance type, and keywords." [ref=e135]
              - row "inspect_instance Returns detailed information about a specific instance, including readable properties, custom attributes, and a summary of its children and descendants." [ref=e136]:
                - cell "inspect_instance" [ref=e137]:
                  - generic [ref=e138]: inspect_instance
                - cell "Returns detailed information about a specific instance, including readable properties, custom attributes, and a summary of its children and descendants." [ref=e139]
            - rowgroup [ref=e140]:
              - row "Luau execution" [ref=e141]:
                - columnheader "Luau execution" [ref=e142]:
                  - generic [ref=e143]: Luau execution
                - columnheader [ref=e144]
            - rowgroup [ref=e145]:
              - row "execute_luau Runs Luau code in Studio. Returns either the result or an error." [ref=e146]:
                - cell "execute_luau" [ref=e147]:
                  - generic [ref=e148]: execute_luau
                - cell "Runs Luau code in Studio. Returns either the result or an error." [ref=e149]
            - rowgroup [ref=e150]:
              - row "Playtesting" [ref=e151]:
                - columnheader "Playtesting" [ref=e152]:
                  - generic [ref=e153]: Playtesting
                - columnheader [ref=e154]
            - rowgroup [ref=e155]:
              - row "start_stop_play Starts or stops playtesting." [ref=e156]:
                - cell "start_stop_play" [ref=e157]:
                  - generic [ref=e158]: start_stop_play
                - cell "Starts or stops playtesting." [ref=e159]
              - row "console_output Retrieves output logs while the game is running." [ref=e160]:
                - cell "console_output" [ref=e161]:
                  - generic [ref=e162]: console_output
                - cell "Retrieves output logs while the game is running." [ref=e163]
              - row "playtest_subagent Spawns a test character that runs through gameplay scenarios." [ref=e164]:
                - cell "playtest_subagent" [ref=e165]:
                  - generic [ref=e166]: playtest_subagent
                - cell "Spawns a test character that runs through gameplay scenarios." [ref=e167]
            - rowgroup [ref=e168]:
              - row "Player input simulation" [ref=e169]:
                - columnheader "Player input simulation" [ref=e170]:
                  - generic [ref=e171]: Player input simulation
                - columnheader [ref=e172]
            - rowgroup [ref=e173]:
              - row "character_navigation Moves the player character to a position or instance." [ref=e174]:
                - cell "character_navigation" [ref=e175]:
                  - generic [ref=e176]: character_navigation
                - cell "Moves the player character to a position or instance." [ref=e177]
              - row "keyboard_input Simulates key presses, key holds, and text input." [ref=e178]:
                - cell "keyboard_input" [ref=e179]:
                  - generic [ref=e180]: keyboard_input
                - cell "Simulates key presses, key holds, and text input." [ref=e181]
              - row "mouse_input Simulates mouse clicks, movement, and scrolling." [ref=e182]:
                - cell "mouse_input" [ref=e183]:
                  - generic [ref=e184]: mouse_input
                - cell "Simulates mouse clicks, movement, and scrolling." [ref=e185]
            - rowgroup [ref=e186]:
              - row "Session management" [ref=e187]:
                - columnheader "Session management" [ref=e188]:
                  - generic [ref=e189]: Session management
                - columnheader [ref=e190]
            - rowgroup [ref=e191]:
              - row "list_roblox_studios Lists all connected Studio instances, including their name, ID, and active status. This is useful when multiple Studio windows are open." [ref=e192]:
                - cell "list_roblox_studios" [ref=e193]:
                  - generic [ref=e194]: list_roblox_studios
                - cell "Lists all connected Studio instances, including their name, ID, and active status. This is useful when multiple Studio windows are open." [ref=e195]
              - row "set_active_studio Sets a Studio instance as active so that all subsequent tool calls target that instance." [ref=e196]:
                - cell "set_active_studio" [ref=e197]:
                  - generic [ref=e198]: set_active_studio
                - cell "Sets a Studio instance as active so that all subsequent tool calls target that instance." [ref=e199]
          - heading "copy header link" [level=2] [ref=e200]:
            - link "copy header link" [ref=e201] [cursor=pointer]:
              - /url: "#enable-the-mcp-server-in-studio"
              - text: Enable the MCP server in Studio
          - paragraph [ref=e202]: "To enable the MCP server in Studio:"
          - list [ref=e203]:
            - listitem [ref=e204]:
              - generic [ref=e205]: Open Assistant.
            - listitem [ref=e206]:
              - generic [ref=e207]: Click … ⟩ Manage MCP Servers.
            - listitem [ref=e208]:
              - generic [ref=e209]: Turn on Enable Studio as MCP server.
          - paragraph [ref=e210]: Once enabled, the settings panel displays the JSON configuration and startup command for your client. When a client connects successfully, a green indicator shows the number of connected clients.
          - heading "copy header link" [level=2] [ref=e211]:
            - link "copy header link" [ref=e212] [cursor=pointer]:
              - /url: "#connect-your-client"
              - text: Connect your client
          - alert [ref=e213]:
            - img [ref=e215]
            - paragraph [ref=e219]: MCP clients can read and modify content in your open Roblox places. Make sure to only connect clients you trust.
          - paragraph [ref=e220]: To connect your client to the server, you can use either a JSON configuration or a CLI command.
          - paragraph [ref=e221]: If your client supports MCP config files, use the JSON configuration. Otherwise, use the CLI command.
          - heading "JSON configuration" [level=5] [ref=e222]
          - paragraph [ref=e223]: Most editors use JSON configuration files for MCP servers. The following examples show complete configurations you can use.
          - paragraph [ref=e224]: If Roblox Studio is your only MCP server, use these configurations as they are. If you're using multiple MCP servers, copy the Roblox_Studio entry and add it to your existing mcpServers dictionary.
          - paragraph [ref=e225]: The configuration depends on your operating system.
          - alert [ref=e226]:
            - img [ref=e228]
            - paragraph [ref=e232]: Your mcp.json file might already contain other entries. When adding the Roblox_Studio configuration, make sure each entry is separated by a comma. Missing commas will result in invalid JSON and prevent the configuration from loading.
          - generic [ref=e235]:
            - generic [ref=e236]:
              - generic [ref=e238]: Windows
              - button "Copy code to clipboard" [ref=e241] [cursor=pointer]:
                - img [ref=e242]
            - separator [ref=e244]
            - code [ref=e246]:
              - generic [ref=e247]:
                - generic [ref=e248]:
                  - generic [ref=e249]: "1"
                  - generic [ref=e250]: "{"
                - generic [ref=e251]:
                  - generic [ref=e252]: "2"
                  - generic [ref=e253]: "\"mcpServers\": {"
                - generic [ref=e254]:
                  - generic [ref=e255]: "3"
                  - generic [ref=e256]: "\"Roblox_Studio\": {"
                - generic [ref=e257]:
                  - generic [ref=e258]: "4"
                  - generic [ref=e259]: "\"command\": \"cmd.exe\","
                - generic [ref=e260]:
                  - generic [ref=e261]: "5"
                  - generic [ref=e262]: "\"args\": ["
                - generic [ref=e263]:
                  - generic [ref=e264]: "6"
                  - generic [ref=e265]: "\"/c\","
                - generic [ref=e266]:
                  - generic [ref=e267]: "7"
                  - generic [ref=e268]: "\"%LOCALAPPDATA%\\\\Roblox\\\\mcp.bat\""
                - generic [ref=e269]:
                  - generic [ref=e270]: "8"
                  - generic [ref=e271]: "]"
                - generic [ref=e272]:
                  - generic [ref=e273]: "9"
                  - generic [ref=e274]: "}"
                - generic [ref=e275]:
                  - generic [ref=e276]: "10"
                  - generic [ref=e277]: "}"
                - generic [ref=e278]:
                  - generic [ref=e279]: "11"
                  - generic [ref=e280]: "}"
          - generic [ref=e283]:
            - generic [ref=e284]:
              - generic [ref=e286]: macOS
              - button "Copy code to clipboard" [ref=e289] [cursor=pointer]:
                - img [ref=e290]
            - separator [ref=e292]
            - code [ref=e294]:
              - generic [ref=e295]:
                - generic [ref=e296]:
                  - generic [ref=e297]: "1"
                  - generic [ref=e298]: "{"
                - generic [ref=e299]:
                  - generic [ref=e300]: "2"
                  - generic [ref=e301]: "\"mcpServers\": {"
                - generic [ref=e302]:
                  - generic [ref=e303]: "3"
                  - generic [ref=e304]: "\"Roblox_Studio\": {"
                - generic [ref=e305]:
                  - generic [ref=e306]: "4"
                  - generic [ref=e307]: "\"command\": \"/Applications/RobloxStudio.app/Contents/MacOS/StudioMCP\""
                - generic [ref=e308]:
                  - generic [ref=e309]: "5"
                  - generic [ref=e310]: "}"
                - generic [ref=e311]:
                  - generic [ref=e312]: "6"
                  - generic [ref=e313]: "}"
                - generic [ref=e314]:
                  - generic [ref=e315]: "7"
                  - generic [ref=e316]: "}"
          - heading "CLI command" [level=5] [ref=e317]
          - paragraph [ref=e318]: Some MCP clients require a CLI command instead of a JSON configuration. The command depends on your operating system.
          - generic [ref=e321]:
            - generic [ref=e322]:
              - generic [ref=e324]: Windows
              - button "Copy code to clipboard" [ref=e327] [cursor=pointer]:
                - img [ref=e328]
            - separator [ref=e330]
            - code [ref=e332]:
              - generic [ref=e335]: cmd.exe /c %LOCALAPPDATA%\Roblox\mcp.bat
          - generic [ref=e338]:
            - generic [ref=e339]:
              - generic [ref=e341]: macOS
              - button "Copy code to clipboard" [ref=e344] [cursor=pointer]:
                - img [ref=e345]
            - separator [ref=e347]
            - code [ref=e349]:
              - generic [ref=e352]: /Applications/RobloxStudio.app/Contents/MacOS/StudioMCP
          - heading "copy header link" [level=3] [ref=e353]:
            - link "copy header link" [ref=e354] [cursor=pointer]:
              - /url: "#claude-code"
              - text: Claude Code
          - paragraph [ref=e355]: "To connect Claude Code:"
          - list [ref=e356]:
            - listitem [ref=e357]:
              - generic [ref=e358]:
                - text: "Open your terminal and run one of the following commands:"
                - list [ref=e359]:
                  - listitem [ref=e360]:
                    - generic [ref=e361]: "Windows: claude mcp add Roblox_Studio -- cmd.exe /c %LOCALAPPDATA%\\Roblox\\mcp.bat"
                  - listitem [ref=e362]:
                    - generic [ref=e363]: "macOS: claude mcp add Roblox_Studio -- /Applications/RobloxStudio.app/Contents/MacOS/StudioMCP"
            - listitem [ref=e364]:
              - generic [ref=e365]: In Claude Code, run /mcp.
            - listitem [ref=e366]:
              - generic [ref=e367]: "Confirm that Roblox_Studio: connected appears in the server list."
          - heading "copy header link" [level=3] [ref=e368]:
            - link "copy header link" [ref=e369] [cursor=pointer]:
              - /url: "#claude-desktop"
              - text: Claude Desktop
          - paragraph [ref=e370]: "To connect Claude Desktop:"
          - list [ref=e371]:
            - listitem [ref=e372]:
              - generic [ref=e373]: In the Claude Desktop app, go to Claude ⟩ Settings....
            - listitem [ref=e374]:
              - generic [ref=e375]:
                - text: In the Developer tab, select Edit Config.
                - list [ref=e376]:
                  - listitem [ref=e377]:
                    - generic [ref=e378]: You can also find the config file at C:\Users\<username>\AppData\Local\Packages\Claude_????\LocalCache\Roaming\Claude\claude_desktop_config.json.
            - listitem [ref=e379]:
              - generic [ref=e380]:
                - text: Add the Roblox_Studio configuration from
                - link "Connect your client" [ref=e381] [cursor=pointer]:
                  - /url: "#connect-your-client"
                - text: to the claude_desktop_config.json file.
            - listitem [ref=e382]:
              - generic [ref=e383]: Restart Claude Desktop by fully quitting and relaunching the application.
            - listitem [ref=e384]:
              - generic [ref=e385]: Locate the MCP server indicator at the bottom-right corner of the chat input window.
            - listitem [ref=e386]:
              - generic [ref=e387]: Click the hammer icon to open the tools panel and verify that Roblox Studio is available.
          - heading "copy header link" [level=3] [ref=e388]:
            - link "copy header link" [ref=e389] [cursor=pointer]:
              - /url: "#visual-studio-code"
              - text: Visual Studio Code
          - alert [ref=e390]:
            - img [ref=e392]
            - paragraph [ref=e396]: VS Code uses servers as the top-level key instead of mcpServers. Make sure your JSON configuration uses servers.
          - paragraph [ref=e397]: You can configure the server at the workspace level, globally, or through the Command Palette. Use a workspace configuration for project-specific setups, or a global configuration to reuse the server across all of your projects.
          - paragraph [ref=e398]: "To connect VS Code:"
          - list [ref=e399]:
            - listitem [ref=e400]:
              - generic [ref=e401]:
                - text: "Choose how you want to configure the server:"
                - list [ref=e402]:
                  - listitem [ref=e403]:
                    - generic [ref=e404]:
                      - text: "For the workspace:"
                      - list [ref=e405]:
                        - listitem [ref=e406]:
                          - generic [ref=e407]: In your project root, create a .vscode/mcp.json file.
                        - listitem [ref=e408]:
                          - generic [ref=e409]:
                            - text: Add the Roblox_Studio configuration from
                            - link "Connect your client" [ref=e410] [cursor=pointer]:
                              - /url: "#connect-your-client"
                            - text: to the file.
                  - listitem [ref=e411]:
                    - generic [ref=e412]:
                      - text: "Globally:"
                      - list [ref=e413]:
                        - listitem [ref=e414]:
                          - generic [ref=e415]: In VS Code, open the Command Palette.
                        - listitem [ref=e416]:
                          - generic [ref=e417]: "Run MCP: Open User Configuration."
                        - listitem [ref=e418]:
                          - generic [ref=e419]:
                            - text: Add the Roblox_Studio configuration from
                            - link "Connect your client" [ref=e420] [cursor=pointer]:
                              - /url: "#connect-your-client"
                            - text: to the mcp.json file.
                  - listitem [ref=e421]:
                    - generic [ref=e422]:
                      - text: "Through the Command Palette:"
                      - list [ref=e423]:
                        - listitem [ref=e424]:
                          - generic [ref=e425]: In VS Code, open the Command Palette.
                        - listitem [ref=e426]:
                          - generic [ref=e427]: "Run MCP: Add Server...."
                        - listitem [ref=e428]:
                          - generic [ref=e429]: Select Command (stdio) and enter a server name.
                        - listitem [ref=e430]:
                          - generic [ref=e431]:
                            - text: Add the Roblox_Studio configuration from
                            - link "Connect your client" [ref=e432] [cursor=pointer]:
                              - /url: "#connect-your-client"
                            - text: .
            - listitem [ref=e433]:
              - generic [ref=e434]:
                - text: "Verify the connection:"
                - list [ref=e435]:
                  - listitem [ref=e436]:
                    - generic [ref=e437]: Open the GitHub Copilot Chat.
                  - listitem [ref=e438]:
                    - generic [ref=e439]: Switch to Agent Mode.
                  - listitem [ref=e440]:
                    - generic [ref=e441]: Click the Tools icon.
                  - listitem [ref=e442]:
                    - generic [ref=e443]: Confirm that Roblox Studio tools appears on the list.
          - heading "copy header link" [level=3] [ref=e444]:
            - link "copy header link" [ref=e445] [cursor=pointer]:
              - /url: "#cursor"
              - text: Cursor
          - paragraph [ref=e446]: You can configure the server using the settings UI or by directly editing the configuration file.
          - paragraph [ref=e447]: "To connect Cursor:"
          - list [ref=e448]:
            - listitem [ref=e449]:
              - generic [ref=e450]:
                - text: "Choose how you want to configure the server:"
                - list [ref=e451]:
                  - listitem [ref=e452]:
                    - generic [ref=e453]:
                      - text: "Through the settings UI:"
                      - list [ref=e454]:
                        - listitem [ref=e455]:
                          - generic [ref=e456]: Go to File ⟩ Preferences ⟩ Cursor Settings.
                        - listitem [ref=e457]:
                          - generic [ref=e458]: Select MCP.
                        - listitem [ref=e459]:
                          - generic [ref=e460]: Click Add new global MCP server.
                        - listitem [ref=e461]:
                          - generic [ref=e462]:
                            - text: Add the Roblox_Studio configuration from
                            - link "Connect your client" [ref=e463] [cursor=pointer]:
                              - /url: "#connect-your-client"
                            - text: .
                  - listitem [ref=e464]:
                    - generic [ref=e465]:
                      - text: "Through the configuration file:"
                      - list [ref=e466]:
                        - listitem [ref=e467]:
                          - generic [ref=e468]: Open ~/.cursor/mcp.json (for global) or .cursor/mcp.json (for project-level).
                        - listitem [ref=e469]:
                          - generic [ref=e470]:
                            - text: Add the Roblox_Studio configuration from
                            - link "Connect your client" [ref=e471] [cursor=pointer]:
                              - /url: "#connect-your-client"
                            - text: to the file.
            - listitem [ref=e472]:
              - generic [ref=e473]:
                - text: "Verify the connection:"
                - list [ref=e474]:
                  - listitem [ref=e475]:
                    - generic [ref=e476]: Go to Cursor Settings ⟩ MCP.
                  - listitem [ref=e477]:
                    - generic [ref=e478]: Confirm that the server is showing a green status indicator.
          - heading "copy header link" [level=3] [ref=e479]:
            - link "copy header link" [ref=e480] [cursor=pointer]:
              - /url: "#antigravity"
              - text: Antigravity
          - paragraph [ref=e481]: "To connect Antigravity:"
          - list [ref=e482]:
            - listitem [ref=e483]:
              - generic [ref=e484]: In Antigravity, click … ⟩ MCP Servers.
            - listitem [ref=e485]:
              - generic [ref=e486]: Click Manage MCP Servers.
            - listitem [ref=e487]:
              - generic [ref=e488]: Click View raw config.
            - listitem [ref=e489]:
              - generic [ref=e490]:
                - text: Add the Roblox_Studio configuration from
                - link "Connect your client" [ref=e491] [cursor=pointer]:
                  - /url: "#connect-your-client"
                - text: to the mcp_config.json file.
            - listitem [ref=e492]:
              - generic [ref=e493]: Refresh the MCP Servers panel to verify that Roblox Studio tools appears in the active tools list.
          - heading "copy header link" [level=3] [ref=e494]:
            - link "copy header link" [ref=e495] [cursor=pointer]:
              - /url: "#other-mcp-clients"
              - text: Other MCP clients
          - paragraph [ref=e496]:
            - text: The Studio MCP server works with any client that supports stdio transport. Use the configuration JSON or CLI command from the
            - link "Connect your client" [ref=e497] [cursor=pointer]:
              - /url: "#connect-your-client"
            - text: section, then follow your client's documentation to add the server configuration. Restart the client to apply your changes.
          - heading "copy header link" [level=2] [ref=e498]:
            - link "copy header link" [ref=e499] [cursor=pointer]:
              - /url: "#use-multiple-studio-instances"
              - text: Use multiple Studio instances
          - paragraph [ref=e500]: You can connect a single MCP client to multiple running instances of Studio at the same time. The server automatically determines which instance to use based on context (for example, if you reference a specific experience or an object that exists only in that instance).
          - paragraph [ref=e501]: You can manually switch instances using list_roblox_studios and set_active_studio.
          - heading "copy header link" [level=2] [ref=e502]:
            - link "copy header link" [ref=e503] [cursor=pointer]:
              - /url: "#verify-your-connection"
              - text: Verify your connection
          - paragraph [ref=e504]: "After setting up your client, verify that the connection is working in Roblox Studio:"
          - list [ref=e505]:
            - listitem [ref=e506]:
              - generic [ref=e507]: Open Assistant.
            - listitem [ref=e508]:
              - generic [ref=e509]: Click … ⟩ Manage MCP Servers.
            - listitem [ref=e510]:
              - generic [ref=e511]: Under Enable Studio as MCP server, check for the green indicator to confirm that the client has connected successfully.
          - heading "copy header link" [level=2] [ref=e512]:
            - link "copy header link" [ref=e513] [cursor=pointer]:
              - /url: "#troubleshooting"
              - text: Troubleshooting
          - paragraph [ref=e514]: "If the server is not showing up, or the tools aren't available:"
          - list [ref=e515]:
            - listitem [ref=e516]:
              - generic [ref=e517]: Restart both Roblox Studio and your MCP client.
            - listitem [ref=e518]:
              - generic [ref=e519]: Verify that the command or binary path is correct and the file exists.
            - listitem [ref=e520]:
              - generic [ref=e521]: Check your JSON syntax. Even a missing comma or bracket can prevent the configuration from loading.
      - generic [ref=e524]:
        - generic [ref=e525]:
          - generic [ref=e526]: ©2026 Roblox Corporation. Roblox, the Roblox logo and Powering Imagination are among our registered and unregistered trademarks in the U.S. and other countries.
          - generic [ref=e527]:
            - link "Terms" [ref=e528] [cursor=pointer]:
              - /url: https://www.roblox.com/info/terms
            - text: ·
            - link "Privacy" [ref=e529] [cursor=pointer]:
              - /url: https://www.roblox.com/info/privacy
            - text: ·
            - link "Accessibility" [ref=e530] [cursor=pointer]:
              - /url: https://www.roblox.com/info/accessibility
            - text: ·
            - link "Support" [ref=e531] [cursor=pointer]:
              - /url: https://www.roblox.com/info/help
        - generic [ref=e532]:
          - link "X" [ref=e533] [cursor=pointer]:
            - /url: https://x.com/Roblox
            - button "X" [ref=e534]:
              - img [ref=e535]
          - link "Facebook" [ref=e537] [cursor=pointer]:
            - /url: https://www.facebook.com/Roblox/
            - button "Facebook" [ref=e538]:
              - img [ref=e539]
          - link "LinkedIn" [ref=e541] [cursor=pointer]:
            - /url: https://www.linkedin.com/company/roblox
            - button "LinkedIn" [ref=e542]:
              - img [ref=e543]
          - link "Instagram" [ref=e545] [cursor=pointer]:
            - /url: https://www.instagram.com/roblox/
            - button "Instagram" [ref=e546]:
              - img [ref=e547]
          - link "YouTube" [ref=e550] [cursor=pointer]:
            - /url: https://www.youtube.com/@RobloxLearn
            - button "YouTube" [ref=e551]:
              - img [ref=e552]
        - link "English" [ref=e555] [cursor=pointer]:
          - /url: https://create.roblox.com/settings/preferences
          - button "English" [ref=e556]:
            - img [ref=e558]
            - generic [ref=e560]: English
  - alert [ref=e561]
  - iframe