- generic [ref=e1]:
  - generic [ref=e3]:
    - generic [ref=e9]:
      - link [ref=e503] [cursor=pointer]:
        - /url: /
        - img [ref=e13]
        - generic [ref=e74]: Creator
      - generic [ref=e77]:
        - combobox [ref=e504] [cursor=pointer]:
          - generic [ref=e79]:
            - img [ref=e505]
            - generic [ref=e506]: AhmadPSN
        - textbox: "126595306"
        - img
        - group
      - link [ref=e507] [cursor=pointer]:
        - /url: /
        - img [ref=e88]
        - generic [ref=e91]: Home
      - link [ref=e508] [cursor=pointer]:
        - /url: /dashboard/creations
        - img [ref=e95]
        - generic [ref=e98]: Creations
      - link [ref=e509] [cursor=pointer]:
        - /url: https://create.roblox.com/docs?navFromCreatorHub=true
        - img [ref=e102]
        - generic [ref=e106]: Learn
      - link [ref=e510] [cursor=pointer]:
        - /url: https://create.roblox.com/store/
        - img [ref=e110]
        - generic [ref=e113]: Store
      - link [ref=e511] [cursor=pointer]:
        - /url: https://devforum.roblox.com
        - img [ref=e117]
        - generic [ref=e122]: Forum
      - separator [ref=e123]
      - link [ref=e512] [cursor=pointer]:
        - /url: /dashboard/devex
        - img [ref=e127]
        - generic [ref=e130]: Finances
      - link [ref=e513] [cursor=pointer]:
        - /url: /dashboard/analytics
        - img [ref=e134]
        - generic [ref=e144]: Analytics
      - link [ref=e514] [cursor=pointer]:
        - /url: https://create.roblox.com/advertise
        - img [ref=e148]
        - generic [ref=e151]: Ads
      - separator [ref=e152]
      - button [ref=e515] [cursor=pointer]:
        - img [ref=e156]
        - generic [ref=e167]: All tools
      - link [ref=e516] [cursor=pointer]:
        - /url: https://roblox.com/
        - img [ref=e171]
        - generic [ref=e174]: Roblox.com
      - button [ref=e517] [cursor=pointer]:
        - img [ref=e178]
        - generic [ref=e182]: Studio
    - generic [ref=e16]:
      - generic [ref=e17]:
        - button [ref=e518] [cursor=pointer]:
          - img [ref=e19]
        - heading [level=1] [ref=e519]: API Extensions
      - generic [ref=e21]:
        - button [ref=e520] [cursor=pointer]:
          - img [ref=e24]
        - button [ref=e521] [cursor=pointer]:
          - img [ref=e189]
        - button [ref=e522] [cursor=pointer]:
          - img [ref=e523]
    - generic [ref=e31]:
      - generic [ref=e249]:
        - generic [ref=e250]:
          - button [ref=e524] [cursor=pointer]:
            - img [ref=e252]
          - generic [ref=e254]: New API Key
          - button [ref=e525] [cursor=pointer]:
            - generic [ref=e366]: Save & Generate Key
        - separator [ref=e256]
        - generic [ref=e258]:
          - button [expanded] [ref=e526] [cursor=pointer]:
            - generic [ref=e262]:
              - generic [ref=e264]: "1"
              - generic [ref=e265]: General Information
            - img [ref=e267]
          - region [ref=e272]:
            - generic [ref=e274]:
              - generic [ref=e275]:
                - generic [ref=e276]:
                  - generic [ref=e277]:
                    - text: Name
                    - generic [ref=e278]: (Required)
                  - paragraph [ref=e279]: Give your API Key a unique name
                - generic [ref=e281]:
                  - generic [ref=e283]:
                    - textbox [ref=e527]:
                      - /placeholder: Name your API Key
                      - text: The Oath dev publisher
                    - group
                  - generic [ref=e285]: 22/64
              - generic [ref=e286]:
                - generic [ref=e287]:
                  - generic [ref=e288]: Description
                  - paragraph [ref=e289]: Enter an optional description for your API key
                - generic [ref=e291]:
                  - generic [ref=e293]:
                    - textbox [ref=e528]:
                      - /placeholder: Enter a description here...
                    - group
                  - generic [ref=e295]: 0/1000
        - generic [ref=e297]:
          - button [expanded] [ref=e529] [cursor=pointer]:
            - generic [ref=e301]:
              - generic [ref=e303]: "2"
              - generic [ref=e304]: Access Permissions
            - img [ref=e306]
          - region [ref=e311]:
            - generic [ref=e313]:
              - generic [ref=e314]:
                - generic [ref=e318]:
                  - img [ref=e319]
                  - combobox [ref=e530]
                  - button [ref=e531] [cursor=pointer]:
                    - img [ref=e324]
                  - group
                - generic [ref=e327]: Set the minimum permissions for your application to minimize impact in case your key gets compromised.
              - generic [ref=e473]:
                - generic [ref=e474]:
                  - generic [ref=e475]:
                    - generic [ref=e476]: universe-places
                    - button [ref=e532] [cursor=pointer]:
                      - img [ref=e478]
                  - generic [ref=e480]:
                    - checkbox [ref=e533] [cursor=pointer]
                    - generic [ref=e486]: Restrict by Experience
                - separator [ref=e487]
                - generic [ref=e490]:
                  - paragraph [ref=e492]: "\"Write\" will apply to all existing places in the experience."
                  - generic [ref=e497]:
                    - combobox [ref=e534]
                    - button [ref=e535] [cursor=pointer]:
                      - img [ref=e501]
                    - group
        - generic [ref=e330]:
          - button [expanded] [ref=e536] [cursor=pointer]:
            - generic [ref=e334]:
              - generic [ref=e336]: "3"
              - generic [ref=e337]: Security
            - img [ref=e339]
          - region [ref=e344]:
            - generic [ref=e346]:
              - generic [ref=e348]:
                - checkbox [ref=e537] [cursor=pointer]
                - text: Restrict which IP addresses this API Key can be used from
              - generic [ref=e353]:
                - generic [ref=e354]:
                  - generic [ref=e356]: Expiration
                  - text: The API Key will expire either on the specified expiration date or after 60 days of inactivity, whichever comes first.
                - generic [ref=e360]:
                  - combobox [ref=e538] [cursor=pointer]: No Expiration
                  - textbox: "0"
                  - img
                  - group
        - generic [ref=e362]: A unique name is required to generate an API key.
        - button [ref=e539] [cursor=pointer]:
          - generic [ref=e369]: Save & Generate Key
      - generic [ref=e39]:
        - generic [ref=e40]:
          - generic [ref=e241]: ©2026 Roblox Corporation. All rights reserved.
          - generic [ref=e41]:
            - link [ref=e540] [cursor=pointer]:
              - /url: https://www.roblox.com/info/terms
              - text: Terms
            - text: ·
            - link [ref=e541] [cursor=pointer]:
              - /url: https://www.roblox.com/info/privacy
              - text: Privacy
            - text: ·
            - link [ref=e542] [cursor=pointer]:
              - /url: https://www.roblox.com/info/accessibility
              - text: Accessibility
            - text: ·
            - link [ref=e543] [cursor=pointer]:
              - /url: https://www.roblox.com/info/help
              - text: Support
            - text: ·
            - button [ref=e544] [cursor=pointer]:
              - generic [ref=e247]: Your Privacy Choices
        - generic [ref=e42]:
          - link [ref=e545] [cursor=pointer]:
            - /url: https://x.com/Roblox
            - button [ref=e546]:
              - img [ref=e45]
          - link [ref=e547] [cursor=pointer]:
            - /url: https://www.facebook.com/Roblox/
            - button [ref=e548]:
              - img [ref=e49]
          - link [ref=e549] [cursor=pointer]:
            - /url: https://www.linkedin.com/company/roblox
            - button [ref=e550]:
              - img [ref=e53]
          - link [ref=e551] [cursor=pointer]:
            - /url: https://www.instagram.com/roblox/
            - button [ref=e552]:
              - img [ref=e57]
          - link [ref=e553] [cursor=pointer]:
            - /url: https://www.youtube.com/Roblox
            - button [ref=e554]:
              - img [ref=e62]
        - link [ref=e555] [cursor=pointer]:
          - /url: https://roblox.com/my/account
          - button [ref=e556]:
            - img [ref=e68]
            - generic [ref=e70]: English
  - alert [ref=e71]
  - dialog "Toggle Experience Restrictions" [ref=e559]:
    - generic [ref=e560]:
      - heading "Toggle Experience Restrictions" [level=2] [ref=e561]
      - paragraph [ref=e563]:
        - paragraph [ref=e564]: Are you sure you want to toggle experience restrictions? Your selected operations and experiences will be lost.
      - generic [ref=e565]:
        - button "Cancel" [ref=e566] [cursor=pointer]:
          - generic [ref=e567]: Cancel
        - button "Continue" [ref=e568] [cursor=pointer]:
          - generic [ref=e569]: Continue